version: '3.8'
services:
  bossabox:
    image: pauloaugusto/bossabox-challenge:latest
    container_name: bossabox
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGOCONNECT: mongodb://mongodbnouser:27017/mydatabase 
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodbnouser
    command: ["npm", "start"]

  mongodbnouser:
    image: mongo:latest
    container_name: mongodbnouser
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
